baseurl      = "https://kurlymeister.github.io/"
title        = "keeks"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[build]
  [build.environment]
    HUGO_VERSION = "0.130.0"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "stuff and nonsense"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "sharing the latest WHS research"
  keywords = "whs, psychosocial"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "keeks"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "stuff and nonsense"

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true


  # Menu

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"


  # Custom footer 

  [params.footer]
    trademark = 2024
    rss = false
    copyright = false
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]


  # Addon: Social icons
  
  [[params.social]]
    name = "email"
    url  = "mailto:kieran.astley@outlook.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kieranastley/"