baseurl      = "https://kurlymeister.github.io/"
title        = "psychsafety.help"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "get in touch below"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "sharing the latest WHS research"
  keywords = "whs, psychosocial"
  images = [""]

  # Theme toggle menu
  enableThemeToggle = true

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  # Colors for favicons
  
  [params.favicon]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "/home"
    logoHomeLink = "/"


  # Menu

[[menu.main]]
    name       = "research"
    url        = "/research/"
    weight     = 1  

[[menu.main]]
    name       = "reports"
    url        = "/reports"
    weight     = 2


  # Custom footer 

  [params.footer]
    trademark = 2024
    rss = false
    copyright = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]


  # Addon: Social icons
  
  [[params.social]]
    name = "email"
    url  = "mailto:kieran.astley@outlook.com"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kieranastley/"